@startuml
interface Buff

Attack : int pierce
Attack : double cooldown
Attack : Damage damage
Attack : int numProjectiles

Upgrade o-- Buff
AttacksBuff ..|> Buff
AddAttack ..|> Buff
AttackList o-- Attack
Tower "1" *--> "5" Upgrade
Tower "1" *--> "5" Upgrade
Tower "1" *--> "5" Upgrade
Tower --> AttackList
@enduml