@startuml
interface Buff

Damage : int base
Damage : int ceramic
Damage : int moab

Attack : int pierce
Attack : double cooldown
Attack : int numProjectiles

Attack -- Damage

Upgrade o-- Buff
AttacksBuff ..|> Buff
AddAttack ..|> Buff
AttackList o-- Attack
Tower "1" *--> "5" Upgrade
Tower "1" *--> "5" Upgrade
Tower "1" *--> "5" Upgrade
Tower --> AttackList
@enduml